# Generated by Django 3.2.6 on 2022-02-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay_id',
            name='age',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='city',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='contact_num',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='email',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='emergency_address',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='emergency_contact_num',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='emergency_name',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='province',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='street',
        ),
        migrations.RemoveField(
            model_name='barangay_id',
            name='zip_code',
        ),
    ]
