# Generated by Django 3.2.6 on 2022-02-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0003_auto_20220221_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_id',
            name='birthday',
            field=models.DateField(default='2022-01-01'),
        ),
    ]
