# Generated by Django 4.0.2 on 2022-02-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0004_barangay_id_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_id',
            name='government_id_or_letter',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='barangay_id',
            name='personal_photo',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='barangay_id',
            name='voters_id',
            field=models.FileField(default='null', upload_to=''),
        ),
    ]
