# Generated by Django 4.0.2 on 2022-02-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0011_barangay_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_id',
            name='landlord_address',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='barangay_id',
            name='landlord_contact_number',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='barangay_id',
            name='landlord_name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
