# Generated by Django 3.2.6 on 2022-03-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0018_remove_barangay_certificate_voters_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_certificate',
            name='document_type',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='barangay_clearance',
            name='document_type',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='barangay_id',
            name='document_type',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate_of_indigency',
            name='document_type',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
