# Generated by Django 3.2.6 on 2022-04-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0021_auto_20220323_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_id',
            name='document_id',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='barangay_certificate',
            name='status',
            field=models.CharField(choices=[('Submitted for Review', 'Submitted for Review'), ('Review Completed', 'Review Completed'), ('Pre-filled Template Verified', 'Pre-filled Template Verified'), ('Printed, Not Paid', 'Printed, Not Paid'), ('Printed, Paid', 'Printed, Paid'), ('Printed, Out for Delivery/Ready for Pickup', 'Printed, Out for Delivery/Ready for Pickup'), ('Delivered/Picked-up', 'Delivered/Picked-up'), ('Rejected', 'Rejected')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='barangay_clearance',
            name='status',
            field=models.CharField(choices=[('Submitted for Review', 'Submitted for Review'), ('Review Completed', 'Review Completed'), ('Pre-filled Template Verified', 'Pre-filled Template Verified'), ('Printed, Not Paid', 'Printed, Not Paid'), ('Printed, Paid', 'Printed, Paid'), ('Printed, Out for Delivery/Ready for Pickup', 'Printed, Out for Delivery/Ready for Pickup'), ('Delivered/Picked-up', 'Delivered/Picked-up'), ('Rejected', 'Rejected')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='status',
            field=models.CharField(choices=[('Submitted for Review', 'Submitted for Review'), ('Review Completed', 'Review Completed'), ('Pre-filled Template Verified', 'Pre-filled Template Verified'), ('Printed, Not Paid', 'Printed, Not Paid'), ('Printed, Paid', 'Printed, Paid'), ('Printed, Out for Delivery/Ready for Pickup', 'Printed, Out for Delivery/Ready for Pickup'), ('Delivered/Picked-up', 'Delivered/Picked-up'), ('Rejected', 'Rejected')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate_of_indigency',
            name='status',
            field=models.CharField(choices=[('Submitted for Review', 'Submitted for Review'), ('Review Completed', 'Review Completed'), ('Pre-filled Template Verified', 'Pre-filled Template Verified'), ('Printed, Not Paid', 'Printed, Not Paid'), ('Printed, Paid', 'Printed, Paid'), ('Printed, Out for Delivery/Ready for Pickup', 'Printed, Out for Delivery/Ready for Pickup'), ('Delivered/Picked-up', 'Delivered/Picked-up'), ('Rejected', 'Rejected')], default='null', max_length=100),
        ),
    ]
