# Generated by Django 3.2.6 on 2022-04-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0022_auto_20220407_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_certificate',
            name='document_id',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='barangay_clearance',
            name='document_id',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate_of_indigency',
            name='document_id',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
