# Generated by Django 3.2.6 on 2022-04-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0028_auto_20220417_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_id',
            name='landlord_address',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='landlord_contact_number',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='landlord_name',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
    ]
