# Generated by Django 3.2.6 on 2022-04-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0032_alter_user_account_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='barangay',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='user_account',
            name='city',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='user_account',
            name='civil_status',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='user_account',
            name='email',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='user_account',
            name='middle_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_account',
            name='nationality',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='user_account',
            name='personal_photo',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='user_account',
            name='province',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='user_account',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='user_account',
            name='street',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='user_account',
            name='zip_code',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
