# Generated by Django 3.2.6 on 2022-02-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0006_alter_barangay_id_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_id',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
