# Generated by Django 4.0.2 on 2022-02-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0010_barangay_clearance_certificate_of_indigency'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_id',
            name='type',
            field=models.CharField(choices=[('Constituent', 'Constituent'), ('Transient', 'Transient')], default='null', max_length=100),
        ),
    ]
