# Generated by Django 4.0.2 on 2022-02-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0012_barangay_id_landlord_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_id',
            name='landlord_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='landlord_contact_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='landlord_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
