# Generated by Django 3.2.6 on 2022-02-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0013_alter_barangay_id_landlord_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_clearance',
            name='type',
            field=models.CharField(choices=[('Bonafide', 'Bonafide'), ('Transient', 'Transient')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='barangay_clearance',
            name='voters_id',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
