# Generated by Django 3.2.6 on 2022-04-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0024_admin_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_account',
            name='password',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='admin_account',
            name='username',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='admin_account',
            name='first_name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='admin_account',
            name='last_name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
