# Generated by Django 3.2.6 on 2022-04-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0025_auto_20220409_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_certificate',
            name='additional_details',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='barangay_clearance',
            name='additional_details',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='barangay_id',
            name='additional_details',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate_of_indigency',
            name='additional_details',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
