# Generated by Django 3.2.6 on 2022-04-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0026_auto_20220409_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_certificate',
            name='latest_contributor',
            field=models.CharField(default='PLACEHOLDER', max_length=100),
        ),
        migrations.AddField(
            model_name='barangay_clearance',
            name='latest_contributor',
            field=models.CharField(default='PLACEHOLDER', max_length=100),
        ),
        migrations.AddField(
            model_name='barangay_id',
            name='latest_contributor',
            field=models.CharField(default='PLACEHOLDER', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate_of_indigency',
            name='latest_contributor',
            field=models.CharField(default='PLACEHOLDER', max_length=100),
        ),
    ]
