# Generated by Django 3.2.6 on 2022-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0033_auto_20220422_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate_of_indigency',
            name='type',
            field=models.CharField(choices=[('Certificate of Indigency', 'Certificate of Indigency')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='government_id_or_letter',
            field=models.FileField(null=True, upload_to='barangay_id'),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='personal_photo',
            field=models.FileField(default='null', upload_to='barangay_id'),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='voters_id',
            field=models.FileField(default='null', upload_to='barangay_id'),
        ),
    ]
