# Generated by Django 3.2.6 on 2022-04-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0034_auto_20220423_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='certificate_of_indigency',
        ),
    ]
