# Generated by Django 3.2.6 on 2022-04-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0035_delete_certificate_of_indigency'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate_of_indigency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(default='null', max_length=100)),
                ('document_type', models.CharField(default='null', max_length=100)),
                ('last_name', models.CharField(default='null', max_length=100)),
                ('first_name', models.CharField(default='null', max_length=100)),
                ('middle_name', models.CharField(default='null', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.DateField(default='2022-01-01')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], default='null', max_length=100)),
                ('nationality', models.CharField(default='null', max_length=100)),
                ('civil_status', models.CharField(default='null', max_length=100)),
                ('email', models.CharField(default='null', max_length=100)),
                ('contact_num', models.CharField(default='null', max_length=100)),
                ('street', models.CharField(default='null', max_length=100)),
                ('city', models.CharField(default='null', max_length=100)),
                ('barangay', models.CharField(default='null', max_length=100)),
                ('province', models.CharField(default='null', max_length=100)),
                ('zip_code', models.CharField(default='null', max_length=100)),
                ('government_id_or_letter', models.FileField(default='null', upload_to='')),
                ('personal_photo', models.FileField(default='null', upload_to='')),
                ('type', models.CharField(choices=[('Bonafide', 'Bonafide'), ('Transient', 'Transient')], default='null', max_length=100)),
                ('date_submitted', models.DateField(default='2022-01-01')),
                ('status', models.CharField(choices=[('Submitted for Review', 'Submitted for Review'), ('Review Completed', 'Review Completed'), ('Pre-filled Template Verified', 'Pre-filled Template Verified'), ('Printed, Not Paid', 'Printed, Not Paid'), ('Printed, Paid', 'Printed, Paid'), ('Printed, Out for Delivery/Ready for Pickup', 'Printed, Out for Delivery/Ready for Pickup'), ('Delivered/Picked-up', 'Delivered/Picked-up'), ('Rejected', 'Rejected')], default='null', max_length=100)),
                ('latest_contributor', models.CharField(default='PLACEHOLDER', max_length=100)),
                ('additional_details', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
