# Generated by Django 3.2.6 on 2022-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0037_remove_user_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_id',
            name='proof_of_payment',
            field=models.FileField(default='null', null=True, upload_to='barangay_id/proof_of_payment'),
        ),
    ]
