# Generated by Django 3.2.6 on 2022-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0038_barangay_id_proof_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_certificate',
            name='proof_of_payment',
            field=models.FileField(default='null', null=True, upload_to='barangay_id/proof_of_payment'),
        ),
        migrations.AddField(
            model_name='barangay_clearance',
            name='proof_of_payment',
            field=models.FileField(default='null', null=True, upload_to='barangay_id/proof_of_payment'),
        ),
        migrations.AddField(
            model_name='certificate_of_indigency',
            name='proof_of_payment',
            field=models.FileField(default='null', null=True, upload_to='barangay_id/proof_of_payment'),
        ),
        migrations.AlterField(
            model_name='barangay_certificate',
            name='additional_details',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='barangay_clearance',
            name='additional_details',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='additional_details',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='certificate_of_indigency',
            name='additional_details',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
