# Generated by Django 3.2.6 on 2022-04-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0040_alter_certificate_of_indigency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate_of_indigency',
            name='type',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
