# Generated by Django 3.2.6 on 2022-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0042_alter_barangay_id_proof_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_id',
            name='proof_of_payment',
            field=models.FileField(default='null', upload_to='payments'),
        ),
    ]
