# Generated by Django 3.2.6 on 2022-04-25 09:23

from django.db import migrations, models
import web_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0043_alter_barangay_id_proof_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_clearance',
            name='government_id_or_letter',
            field=models.FileField(default='null', upload_to=web_portal.models.path_and_rename_barangay_clearance),
        ),
        migrations.AlterField(
            model_name='barangay_clearance',
            name='personal_photo',
            field=models.FileField(default='null', upload_to=web_portal.models.path_and_rename_barangay_clearance),
        ),
        migrations.AlterField(
            model_name='barangay_clearance',
            name='proof_of_payment',
            field=models.FileField(default='null', null=True, upload_to='barangay_id'),
        ),
    ]
