# Generated by Django 3.2.6 on 2022-04-25 09:51

from django.db import migrations, models
import web_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0045_alter_barangay_clearance_proof_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_clearance',
            name='personal_photo',
            field=models.FileField(default='null', upload_to=web_portal.models.path_and_rename_personal_photo_barangay_clearance),
        ),
    ]
