# Generated by Django 3.2.6 on 2022-04-25 09:54

from django.db import migrations, models
import web_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0046_alter_barangay_clearance_personal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_certificate',
            name='government_id_or_letter',
            field=models.FileField(default='null', upload_to=web_portal.models.path_and_rename_barangay_certificate),
        ),
        migrations.AlterField(
            model_name='barangay_certificate',
            name='personal_photo',
            field=models.FileField(default='null', upload_to=web_portal.models.path_and_rename_personal_photo_barangay_certificate),
        ),
        migrations.AlterField(
            model_name='barangay_certificate',
            name='proof_of_payment',
            field=models.FileField(default='null', null=True, upload_to=web_portal.models.path_and_rename_pop_barangay_certificate),
        ),
    ]
