# Generated by Django 3.2.6 on 2022-04-25 09:55

from django.db import migrations, models
import web_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0047_auto_20220425_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate_of_indigency',
            name='government_id_or_letter',
            field=models.FileField(default='null', upload_to=web_portal.models.path_and_rename_certificate_of_indigency),
        ),
        migrations.AlterField(
            model_name='certificate_of_indigency',
            name='personal_photo',
            field=models.FileField(default='null', upload_to=web_portal.models.path_and_rename_personal_photo_certificate_of_indigency),
        ),
        migrations.AlterField(
            model_name='certificate_of_indigency',
            name='proof_of_payment',
            field=models.FileField(default='null', null=True, upload_to=web_portal.models.path_and_rename_pop_certificate_of_indigency),
        ),
    ]
