# Generated by Django 3.2.6 on 2022-04-25 09:57

from django.db import migrations, models
import web_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0048_auto_20220425_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_id',
            name='government_id_or_letter',
            field=models.FileField(null=True, upload_to=web_portal.models.path_and_rename_barangay_id),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='personal_photo',
            field=models.FileField(default='null', upload_to=web_portal.models.path_and_rename_personal_photo_barangay_id),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='proof_of_payment',
            field=models.FileField(default='null', upload_to=web_portal.models.path_and_rename_pop_barangay_id),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='voters_id',
            field=models.FileField(default='null', upload_to=web_portal.models.path_and_rename_voters_barangay_id),
        ),
    ]
