# Generated by Django 3.2.6 on 2022-04-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0049_auto_20220425_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_certificate',
            name='personal_photo',
            field=models.FileField(default='null', upload_to=''),
        ),
    ]
