# Generated by Django 3.2.6 on 2022-04-25 13:38

from django.db import migrations, models
import web_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0050_alter_barangay_certificate_personal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_certificate',
            name='personal_photo',
            field=models.FileField(default='null', upload_to=web_portal.models.path_and_rename_personal_photo_barangay_certificate),
        ),
    ]
