# Generated by Django 3.2.6 on 2022-05-09 07:18

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0052_alter_barangay_id_personal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_id',
            name='personal_photo',
            field=models.FileField(default='null', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='path_and_rename_personal_photo_barangay_id'),
        ),
    ]
