# Generated by Django 3.2.6 on 2022-05-09 09:06

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0053_alter_barangay_id_personal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_id',
            name='government_id_or_letter',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='personal_photo',
            field=models.FileField(default='null', storage=gdstorage.storage.GoogleDriveStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='barangay_id',
            name='voters_id',
            field=models.FileField(default='null', storage=gdstorage.storage.GoogleDriveStorage(), upload_to=''),
        ),
    ]
