# Generated by Django 3.2.6 on 2022-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0054_auto_20220509_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_clearance',
            name='submitted_by',
            field=models.CharField(default='AnonymousUser', max_length=100),
        ),
    ]
