# Generated by Django 3.2.6 on 2022-05-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0055_barangay_clearance_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay_certificate',
            name='submitted_by',
            field=models.CharField(default='AnonymousUser', max_length=100),
        ),
        migrations.AddField(
            model_name='barangay_id',
            name='submitted_by',
            field=models.CharField(default='AnonymousUser', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate_of_indigency',
            name='submitted_by',
            field=models.CharField(default='AnonymousUser', max_length=100),
        ),
    ]
