# Generated by Django 3.2.6 on 2022-05-09 12:17

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0056_auto_20220509_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay_id',
            name='proof_of_payment',
            field=models.FileField(default='null', storage=gdstorage.storage.GoogleDriveStorage(), upload_to=''),
        ),
    ]
