# Generated by Django 3.2.6 on 2022-05-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0061_barangay_clearance_blood_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay_clearance',
            name='blood_type',
        ),
        migrations.AddField(
            model_name='barangay_id',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], default='null', max_length=100),
        ),
    ]
